### ISSUE TITLE
Handle failures of bumpversion more transparently

### ISSUE THREAD

**Issue by myddrin** [EdgyEdgemond/changelog-gen#51]
When bumpversion fails to find a version number in a file to update it fails but the logs are swallowed. This makes it hard to realise that a mistake should be fixed (quite common when adding a file with a version number before a merge).
We should also verify that all other changes are reverted if bump version failed (e.g. tags).

**Comment by myddrin** [comment]
Other scenario: when using changelog-gen if bumpversion fails (e.g. the tag already exists) we currently keep the 2 commits that updated the files and generated the changelog. We should change so that the results are removed on failure.

**Comment by EdgyEdgemond** [comment]
https://github.com/EdgyEdgemond/changelog-gen/issues/36
sounds similar to this one :)

**Comment by myddrin** [comment]
Yes it's the same
