### ISSUE TITLE
Prevent promotion when no changelog files are present but a release is triggered

### ISSUE THREAD

**Issue by myddrin** [EdgyEdgemond/changelog-gen#52]
This would be a configuration option to reject a promotion when no changelog files are present, with a command line argument to override it (like all options).

**Comment by EdgyEdgemond** [comment]
Do you mean no files in `./release_notes` or no `CHANGELOG.md` exists?

**Comment by EdgyEdgemond** [comment]
on assumption of the first scenario, PR opened
