### ISSUE TITLE
Unsupported extension in release_notes error is confusing

### ISSUE THREAD

**Issue by myddrin** [EdgyEdgemond/changelog-gen#54]
```
(scrapers-3.7.12) ~/workspace/scrapers on master 16:03% changelog-gen       
Unsupported CHANGELOG section txt
Aborted!
```

because one file has `.txt` instead of one of the configured extensions.

We should make it clearer it’s an extension (maybe give filename?)

**Comment by EdgyEdgemond** [comment]
is the `.txt` in release notes, or `CHANGELOG.txt` exists in the repository?

In release_notes, file names are in the format `{issue}` or `{issue}.{section}`. If there is an `x.txt` file in there, it would pick up `txt` as the section, and map that to the configured sections, raising the above error as the section `txt` is not one that has been configured.

**Comment by myddrin** [comment]
Yes, it's only to make the error of an invalid section more obvious by listing the filename if possible, something like
```
Unsupported CHANGELOG section txt derived from release_notes/1234.txt
```
